apiVersion : v1
#kind: List
items :
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    creationTimestamp: null
    labels:
      app.kubernetes.io/name: mongodb
      app.kubernetes.io/part-of: penfold-bot
    name: mongodb
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  status: {}
- apiVersion: v1
  kind: Secret
  data:
    database-admin-password: aW5kR3RzNmlZdzZZTFZ3Nw==
    database-password: bFlMVXhSNjVwa0tKamdlMw==
    database-user: dXNlcldHWA==
    mattermost-password:  bFlMVXhSNjVwa0tKamdlMw==
  metadata:
    creationTimestamp: null
    labels:
      app.kubernetes.io/name: penfold-bot
      app.kubernetes.io/part-of: penfold-bot
    name: penfold-bot
- apiVersion: v1
  kind: ConfigMap
  data:
    DATABASE_SERVICE_NAME: mongodb
    EXPRESS_PORT: "8080"
    HUBOT_LOG_LEVEL: debug
    MATTERMOST_GROUP: developers
    MATTERMOST_HOST: chat.openshift.io
    MATTERMOST_USER: penfold_TEST
    MONGODB_DATABASE: penfolddb
    MONGODB_HOST: mongodb
  metadata:
    creationTimestamp: null
    labels:
      app.kubernetes.io/name: penfold-bot
      app.kubernetes.io/part-of: penfold-bot
    name: penfold-config
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    labels:
      app.kubernetes.io/name: mongodb
      app.kubernetes.io/part-of: penfold-bot
    name: mongodb
  spec:
    replicas: 1
    strategy:
      activeDeadlineSeconds: 21600
      recreateParams:
        timeoutSeconds: 600
      resources: {}
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app.kubernetes.io/name: mongodb
          app.kubernetes.io/part-of: penfold-bot
        name: mongodb
      spec:
        containers:
        - env:
          - name: MONGODB_USER
            valueFrom:
              secretKeyRef:
                key: database-user
                name: penfold-bot
          - name: MONGODB_PASSWORD
            valueFrom:
              secretKeyRef:
                key: database-password
                name: penfold-bot
          - name: MONGODB_DATABASE
            value: penfolddb
          - name: MONGODB_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                key: database-admin-password
                name: penfold-bot
          image: registry.access.redhat.com/rhscl/mongodb-32-rhel7:latest
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 27017
            timeoutSeconds: 1
          name: mongodb
          ports:
          - containerPort: 27017
            protocol: TCP
          readinessProbe:
            exec:
              command:
              - /bin/sh
              - -i
              - -c
              - mongo 127.0.0.1:27017/$MONGODB_DATABASE -u $MONGODB_USER -p $MONGODB_PASSWORD
                --eval="quit()"
            failureThreshold: 3
            initialDelaySeconds: 3
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              memory: 512Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /var/lib/mongodb/data
            name: mongodb-data
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - name: mongodb-data
          persistentVolumeClaim:
            claimName: mongodb
    test: false
    selector:
      app.kubernetes.io/name: mongodb
      app.kubernetes.io/part-of: penfold-bot
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - mongodb
        from:
          kind: ImageStreamTag
          name: mongodb:3.2
          namespace: openshift
      type: ImageChange
    - type: ConfigChange
